### ISSUE TITLE
Make rotation ramdomization optional 

### ISSUE THREAD

**Issue by eredrine** [alberttwong/MMM-iFrame#11]
Hello,

Thanks for the great work here! Works really well.

Would it be possible to add in the config an option to make the rotation non-random?

That would be perfect to ensure the same sequence of content gets looped through.

Thanks again!

**Comment by alberttwong** [comment]
Just to set the right expectations, this module is not a commercial open source project. People are donating their free time. If you'd like the feature, feel free to vote it up but better is to pay a developer to write the features you want.
