### ISSUE TITLE
Nest cam stream autoplay?

### ISSUE THREAD

**Issue by matthewsadd** [alberttwong/MMM-iFrame#13]
Is anyone else using this module to display the stream from a nest cam?

Mine is all set up but for some annoying reason the stream in the iframe doesn't autoplay despite adding the ?autoplay=1 to the end of the stream url

I've seen on a few other forums that it may be down to the specific web browser being used and another saying it is because the stream contains audio (I've tried turning off the microphone in the nest camera settings and this doesn't seem to make a difference)?

Any help appreciated!

Cheers

Matt

**Comment by alberttwong** [comment]
I have nest pro and they work just fine.

**Comment by matthewsadd** [comment]
What do you mean by nest pro? I have the 'standard' nest cam - https://nest.com/cameras/nest-cam-indoor/overview/ and a nest aware subscription for the alerts and cloud recording. 

My link is https://video.nest.com/embedded/live/usyVvqtZMB?autoplay=1

When my magicmirror loads up in the iframe I get the first image which remains static... but I can use the mouse to click on the image to start live playback (the icon top left then goes blue). (I'm yet to build the mirror frame etc so just have it testing on a TV at the moment).

![img_0351](https://user-images.githubusercontent.com/40912193/42772666-11ed6370-8923-11e8-916f-5ee31bc2abbc.JPG)
![img_1197](https://user-images.githubusercontent.com/40912193/42772681-18dbf0e8-8923-11e8-918d-3bd10c25347c.JPG)

As a kind of work around I have put the same url in twice and configured the refresh rate down to a few seconds to try and force it to reload... I've seen lots of other people with issues getting nest streams to autoplay so I'd be interested to know if I'm missing something!

**Comment by YangVincent** [comment]
I have the same issue here; have the nest doorbell and cam. It seems also from what links I've seen, that adding ?autoplay=1 doesn't autoplay anything at all. Perhaps this is a Nest issue; there's several reviews on their boards as well.
