### ISSUE TITLE
Clean iFrame cache...

### ISSUE THREAD

**Issue by theramez** [alberttwong/MMM-iFrame#14]
greetings..
If the iFrame assigned to a web page, How can I clean it's cache?
removing electron cache didn't help.

thanks in advance...

**Comment by alberttwong** [comment]
Since the iframe is just a browser, you should be able to do browser things.    You can try deleting the browser cache directory or load the normal browser and use the menus to clear cache.

**Comment by theramez** [comment]
> 
> 
> Since the iframe is just a browser, you should be able to do browser things. You can try deleting the browser cache directory or load the normal browser and use the menus to clear cache.

sorry I tried that but still that module cache (if assigned to view web page that stores cache) totally different than the default pi browser cache whether it's a chromium,kweb...etc? 
I belive that iFrame stores some data in electron cache or something similar.

**Comment by theramez** [comment]
> 
> 
> The only other way is maybe to build a cache clear button via javascript.

thanks, I'm not a programmer so can't do that.....anyway thanks for help 👍
