### ISSUE TITLE
MMM-iFrame does not show - Create config file error

### ISSUE THREAD

**Issue by Canguingo** [alberttwong/MMM-iFrame#15]
Hi, I am trying to use this module but it doesn't work. I might be doing something wrong as I am new to this.

I have cloned this to modules folder under MagicMirror. This is my code:

			module: 'MMM-iFrame',
			header: 'Het weer'
			position: 'top_right',	// This can be any of the regions.
			config: {
				url: "https://gadgets.buienradar.nl/gadget/radarfivedays",
				width: "100%",  // Optional. Default: 100%
				height: "100px" // Optional. Default: 100px
				}
		},

Any help would be grate! Thanks in advance!

**Comment by Canguingo** [comment]
additionally, would it be possible to use a widget code like this?: 

<div style="font-family: Arial;background-color: #fbfbfb;border: 1px solid #e7e7e7;width: 145px;height: 105px;-moz-box-shadow: 0 0 2px 1px #e7e7e7;-webkit-box-shadow: 0 0 2px 1px #e7e7e7;box-shadow: 0 0 2px 1px #e7e7e7;overflow: hidden; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px;"><div style="width: 145px;height: 105px;"><div style="margin:7px 10px;"><iframe id="widget-frame" src="//www.weeronline.nl/Go/ExternalWidgetsNew/OneDayCitySmall?gid=4058223&temperatureScale=Celsius&defaultSettings=True" width="125" height="60" frameborder="0" scrolling="no" style="border: none;" allowtransparency="true"></iframe><a href="//www.weeronline.nl/Europa/Nederland/Amsterdam/4058223" style="display: block;height: 25px;width: 113px;margin: 0px 10px 8px 0px;outline: none;text-decoration: none;" title="Weeronline.nl - Meer weer in Amsterdam" target="_blank"><img src="//www.weeronline.nl/Shared/Images/widget/new-widget-logo-color.png" width="113" height="25" alt="Weeronline.nl - Meer weer in Amsterdam" style="border: none;background-color: transparent;box-shadow: none;" /></a></div></div></div>

**Comment by alberttwong** [comment]
> Hi, I am trying to use this module but it doesn't work. I might be doing something wrong as I am new to this.
> 
> I have cloned this to modules folder under MagicMirror. This is my code:
> 
> ```
> 		module: 'MMM-iFrame',
> 		header: 'Het weer'
> 		position: 'top_right',	// This can be any of the regions.
> 		config: {
> 			url: "https://gadgets.buienradar.nl/gadget/radarfivedays",
> 			width: "100%",  // Optional. Default: 100%
> 			height: "100px" // Optional. Default: 100px
> 			}
> 	},
> ```
> 
> Any help would be grate! Thanks in advance!

This looks right.

**Comment by alberttwong** [comment]
> additionally, would it be possible to use a widget code like this?:
> 
> div style="font-family: Arial;background-color: #fbfbfb;border: 1px solid #e7e7e7;width: 145px;height: 105px;-moz-box-shadow: 0 0 2px 1px #e7e7e7;-webkit-box-shadow: 0 0 2px 1px #e7e7e7;box-shadow: 0 0 2px 1px #e7e7e7;overflow: hidden; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px;">
> <iframe id="widget-frame" src="//www.weeronline.nl/Go/ExternalWidgetsNew/OneDayCitySmall?gid=4058223&temperatureScale=Celsius&defaultSettings=True" width="125" height="60" frameborder="0" scrolling="no" style="border: none;" allowtransparency="true"></iframe>Weeronline.nl - Meer weer in Amsterdam
> </div

You'd have to try.  It's not a regular iframe.   You may have to strip it down to the bare settings.

**Comment by alberttwong** [comment]
have you looked at logs?

**Comment by Canguingo** [comment]
Albert, many thanks for assisting. 
I've been able to see the header on the MagicMirror, thereunder should go the iframe-module. however it is black. I see nothing.

this is the code, which is the same as before but with one "}" less at the end:
{
			module: "MMM-iFrame",
			header: "Het weer",
			position: "top_right",	// This can be any of the regions.
			config: {
				url: "https://gadgets.buienradar.nl/gadget/zoommap/?lat=52.13917&lng=5.04167&overname=2&zoom=13&naam=Maarssen&size=2&voor=0",
				width: "100%",  // Optional. Default: 100%
				height: "256px" // Optional. Default: 100px
				}
		},

<img width="631" alt="knipsel2" src="https://user-images.githubusercontent.com/45333495/48983900-023ce880-f0f5-11e8-9dfe-a405a92593b9.PNG">

on the top-right is where the module should appear, under "HET WEER".

(sorry about confusion regarding uploading files. I just meant where the clone should be installed)

logs... uhmmm (?)

**Comment by Canguingo** [comment]
I think this is what you are looking for? logs...?
<img width="616" alt="knipsel3" src="https://user-images.githubusercontent.com/45333495/48983964-01f11d00-f0f6-11e8-9780-5ecb99946f95.PNG">

and 2nd part:

<img width="565" alt="knipsel4" src="https://user-images.githubusercontent.com/45333495/48983970-0ddcdf00-f0f6-11e8-8b02-fe814c02f601.PNG">

does this help?

**Comment by Canguingo** [comment]
So you don't have a solution?

**Comment by alberttwong** [comment]
Nope.    You'll have to figure out on your own.   This is open source so that means you have the source code to fix it.

**Comment by alberttwong** [comment]
If you'd like help with this issue, consider sponsoring the issue.  https://issuehunt.io/repos/93804431
