### ISSUE TITLE
this module was working until a new pull request today

### ISSUE THREAD

**Issue by Gavin-McLeod** [alberttwong/MMM-iFrame#17]
The iFrame simply stopped showing after updating today by doing a git pull.  No errors reported in Dev Tools, and the modules appears to be cycling through URLS, but nothing is rendered in the display.

		{
			disabled:false,
			module: 'MMM-iFrame',
			position: 'top_center',	// This can be any of the regions.
			config: {
				// See 'Configuration options' for more information.
					url: ["http://images.drivebc.ca/bchighwaycam/pub/cameras/352.jpg", 
					      "http://images.drivebc.ca/bchighwaycam/pub/cameras/351.jpg",
					      "http://images.drivebc.ca/bchighwaycam/pub/cameras/349.jpg",
					      "http://images.drivebc.ca/bchighwaycam/pub/cameras/350.jpg"],  // as many URLs you want or you can just ["ENTER IN URL"] if single URL.
					updateInterval: 15 * 1000, // rotate URLs every 15 seconds
					height:"315px", 
					width:"420px",
			}
		},

**Comment by IRand1** [comment]
Same problem here! Is it possible to get the old version that works?

**Comment by alberttwong** [comment]
You'd have to go to MM and look for that old version.
