### ISSUE TITLE
[Suggestion/Request] Ability to switch between URLs by notification

### ISSUE THREAD

**Issue by smowk** [alberttwong/MMM-iFrame#20]
Hi @alberttwong,

First of all, I have to say thank you for this great module; I love the ability to have multiple URLs to switch between.

This is not an issue, is only a suggestion; I think that adding the ability to switch between URLs by notifications would be a great addition to this module, so you can change what is displayed in the iFrame whenever you want, instead of waiting for the updateInterval.

The updateInterval is great as a security system (switch between cameras) configuration but for watching various streams or certain pages ..not so much.

I see a lot of potential in such a feature, personally, I'm using this module to display my Home Assistant UI on the mirror but if I could change the web pages on demand I would add a physical remote to my configuration and voice control through Google Assistant/Alexa.

Thank you

**Comment by pooyasa** [comment]
Hi @smowk smowk,

Here I made some changes on the original JScode.
by using this code, you can change Urls by sending notifications "pooya" and payloads 1,2,... .
you can change notification name and  payload later.
Hope I helped.





Module.register("pooyaframe",{
		// Default module config.
		defaults: {
                  frameWidth: "300",
						width:"100%",
                  updateInterval: 0.5 * 60 * 1000,
                  url: ["http://magicmirror.builders/"],
                  scrolling: "no"
		},

        start: function () {
                self = this;
                var count = 0;
                window.strurl=0;
           
	},

resume: function() {
   console.log("Resuming");
   return this.getDom();
},
        getStyles: function() {
                return [
                        "MMM-iFrame.css",
                ];
        },

        // Override dom generator.

	getDom: function() {

                var { width, height } = this.config;
                var wrapper = document.createElement("div");
                
                wrapper.className = "mmm-iframe"
                wrapper.style.width = `${this.config.frameWidth}px`;

                var html = `
                        <div class="mmm-iframe-wrapper" style="padding-top: ${100 / (width / height)}%;">`;
                console.log(window.strurl);
                if(window.strurl>0){        
                        html+=`
                                <iframe
                                        src="${this.config.url[window.strurl-1]}"
                                        width="${width}"
                                        height="${height}"
                                        scrolling="${this.config.scrolling}"
                                ></iframe>`;}
                                
                        html+=`        
                        </div>
                `;

                wrapper.insertAdjacentHTML("afterbegin", html);

		return wrapper;
	},
	
	
    notificationReceived: function(notification, payload,sender) {
        if (notification == "pooya") {  
			window.strurl=payload;     
			console.log(window.strurl);           
                        this.updateDom();
            }


            },
	

});

**Comment by smowk** [comment]
@pooyasa thank you!
Really appreciate this
