### ISSUE TITLE
issue with module

### ISSUE THREAD

**Issue by sainiaj** [alberttwong/MMM-iFrame#3]
this module use to work for me and recently having huge issues i use to use it to stream  ip camera to mirror however not workin any more 

{
                module: 'MMM-iFrame',
                position: 'bottom_bar',
                config: {
                                //url: ["http://192.168.1.200/videostream.cgi?user=xxxx&pwd=xxxx"],
                                url: ["http://www.qygjxz.com/data/out/193/3856596-random-image.png"],
                                updateInterval: 0.5 * 60 * 1000,
                                width: "100%", // Optional. Default: 100%
                                height: "100px" //Optional. Default: 100px
                }
        },

Please tell me what am i doing wrong

**Comment by Jakobseja** [comment]
I'm having the same issue. The iFrame doesn't seem to work, just a blank spot.

**Comment by JustinStamey** [comment]
same issue, no resolution?

**Comment by alberttwong** [comment]
I haven't had time to debug this.   Do you know what the logs say?

**Comment by alberttwong** [comment]
I can't help without logs so I can understand what is the issue.

**Comment by alberttwong** [comment]
Closing because no logs.
