### ISSUE TITLE
Iframe doesn't work

### ISSUE THREAD

**Issue by chassain** [alberttwong/MMM-iFrame#4]
hello,

this module can be great for me because i'm using different webcam live on youtube. But it doesn't work with the simple example. Is there a solution please or something changed ?
Thanks

**Comment by alberttwong** [comment]
I would need logs.  Can you provide them?

**Comment by chassain** [comment]
Hello albert.

Sorry i'm new on raspberry. Here my configuration : 
{
			module: "MMM-iFrame",
			disabled: true,
			position: "center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/FAE_qcnrcMw?rel=0&amp;autoplay=1"], 	//londres
				updateInterval: 0.5 * 60 * 1000, // rotate URLs every 30 seconds
				width: "100%", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
			}
		},
How can i looking for logs ?

**Comment by chassain** [comment]
normaly it's false on disabled, not in my example

**Comment by chassain** [comment]
Do i need to modify my package.json like you ? (I'm noob)

**Comment by chassain** [comment]
npm WARN postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0 but none was installed.

**Comment by chassain** [comment]
hello albert,

can you help me (step by step) please ?

**Comment by alberttwong** [comment]
Here's something that may help you.  There should be logs generated.   You just have to find the location and get it.  https://forum.magicmirror.builders/topic/198/flushing-pm2-logs

**Comment by alberttwong** [comment]
Closing because no logs.
