### ISSUE TITLE
Autosizing a picture into the iFrame

### ISSUE THREAD

**Issue by jwmaas** [alberttwong/MMM-iFrame#6]
The snap I take from my Foscam C2 IP camera is 1280x720 pixels. It does not fit the iFrame. In fact the iFrame only shows a very small portion of the picture. 

I would prefer not enlarging the iFrame because it would become too big. It is nicely sized with the other content on the left size of the mirror.
How do I resize the picture I receive from the url to automatically fit the iFrame?

**Comment by alberttwong** [comment]
If you can't generate the right sized image, then that means you have to modify the code.
