### ISSUE TITLE
image reloading from cache

### ISSUE THREAD

**Issue by idoroseman** [alberttwong/MMM-iFrame#7]
i have used a link to a dynamicly rendered image url. it seems that MM shows a cached version of the image. tried adding <meta http-equiv="pragma" content="no-cache"> to index.html but did not solve. ended up modifing 
futureURL = this.config.url[url_index] + "?random=" + (new Date()).getTime();
might not be best solution, but works for me

**Comment by idoroseman** [comment]
my bad, i've missed the (this.config.url.length > 1) on the update loop. changed the 1 to 0, waiting till tommorow to see if it fixes the problem

**Comment by alberttwong** [comment]
Did it fix it?

**Comment by idoroseman** [comment]
yep
